### ISSUE TITLE
Button starting point 

### ISSUE THREAD

**Issue by neptunevinus** [Slip-Up/minimal-ui#1]
I have problem with OK button when I'm dead and only return button show like this

![Screenshot 2021-08-04 103229](https://user-images.githubusercontent.com/56562799/128118645-8780a7da-6e56-4791-b4c6-dc0bc7588086.png)

Thank you for 4k version, I really like this UI mod

**Comment by Slip-Up** [comment]
This should be resolved now in the latest version.  Let me know if there is still an issue for some reason
